# Use postgres/example user/password credentials

services:
  db:
    image: pgvector/pgvector:0.8.1-pg18-trixie
    container_name: postgres-db
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    env_file:
      - .db-env
    ports:
      - 54321:5432
  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      restart: always
      ports:
        - 8888:80
      env_file:      
        - .db-env      
      depends_on:
        - db
      volumes:
        - /home/user/project/savor_app/pgadmin:/var/lib/pgadmin

